sensors/ev3_uart_sensor.h
sensors/ev3_uart_sensor_core.c
sensors/ev3_uart_sensor_defs.c
sensors/ev3_uart_sensor_ld.c
sensors/ms_ev3_smux.c
sensors/nxt_i2c_sensor_defs.c

Also `EV3_UART_SENSOR_NAME(suffix)` macros has been added into `ev3_uart_sensor.h`.

Fix incorrect 'driver_name' attribute values for EV3 UART sensors

---

sensors/nxt_i2c_sensor_defs.c

Typo in ms-absolute-imu documentation

---

motors/rcx_motor_defs.c

Probably copied and forgot to change (from NXT motor)

part number of PF_M_MOTOR typo in motor doc

---

include/lego_sensor_class.h
sensors/lego_sensor_class.c
user/user_lego_sensor.c
user/user_lego_sensor.h

Added code per changes discussed earlier. I left the initial copy operation using `snprintf()` to handle the case of the echo passing in a non-terminated string (just in case)
Interestingly, you cannot write to a sysfs text attribute a string with embedded linefeeds - the kernel will break it into multiple writes and only the last string will stick.
We may be able to take advantage of that later when we do a framebuffer daemon (maybe)

Finish initial support for text_value

---

motors/rcx_led.c

The mode can be `auto tacho-motor dc-motor led raw` not `rcx-led`

Doc update only: mode "rcx-led" should be "led

---

checkpatch.sh

Fix travis always failing because of extra junk generated in github diff.

Ignore bad signoff in CI

---

checkpatch.sh

GitHub API adds some http header lines that are picked up by checkpatch
and cause it to fail.

CI: ignore extra header lines added by GitHub

---

sensors/nxt_i2c_sensor.h
sensors/nxt_i2c_sensor_core.c
sensors/nxt_i2c_sensor_defs.c
sensors/other_sensor_defs.c

@dlech Please take a look. No testing yet, since I'm wanting to make sure it will be safe before I do.
I don't think this is quite right - the scaling looks to me like I should not need to do what I am doing, but the raw_min and raw_max are u32 and I need negative values. Hence the approach I'm taking.
I'm also not sure about how mode state is retained - the device has a variety of modes (word width and one-shot v continuous), but (sanely) imperial is not supported, so unit mode state needs to be retained somewhere else - I am assuming the lego sensor module handles that, but I can't find any indication of that.
Anyway, when you have time please make some suggestions.

Add NXT Temperature Sensor support

---

sensors/nxt_i2c_sensor_defs.c

I think I misinterpreted the meaning behind the range in these comments - thinking it was the post-scaled-range. So this fixes that.
@dlech Please take a look.

Use unscaled values in value range comment

---

brickpi/brickpi_ports_in.c

This clarifies the need to send the address to `set_device`.
@dlech Please take a look.
(Squash, rebase onto master and add reference to 640 and 642 in commit message prior to merge).

Clarify need for address with NXT/I2C set_device

---

sensors/ev3_uart_sensor_defs.c

This is just docs update, in my tests ev3gyro overflows if spinned too many times (as opposed to
getting stuck). If somebody else also tested it maybe there are diffrent
versions of ev3gyro.

ev3gyro overflow

---

sensors/ev3_uart_sensor_ld.c

Dereferencing through NULL pointer, probably because of reversed order of two lines of code. 
Here lines reversed so that they are not reversed, huh.

Uart line discipline bug

---

brickpi/brickpi_i2c_sensor.c

Added link to new BrickPi Input Port 5 docs and information that it's not in BrickPi+.

Brickpi docs update

---

sensors/ev3_uart_sensor_ld.c

This callback is preferred over receive_buf since it returns the count
of the bytes that were actually received.
Issue: ev3dev/ev3dev#671

ev3 uart: use receive_buf2

---

sensors/ev3_uart_sensor_ld.c

0 is a valid value for cmd2. It means that there is one mode.
Issue: ev3dev/ev3dev#663

ev3 uart: Fix sensors with only 1 mode not detected

---

ev3/legoev3_motor.c

- Add parenthesis to force multiplication before division in calculation
of the new_speed_sp because division binds higher than multiplication.

Fix defect in calculation of new_speed_sp

---

checkpatch.sh
user/Makefile
user/user_led.c
user/user_led.h
user/user_lego_configfs.c

LEDs are configured in configfs. Ideally, there will be a character device
that can be used by the userspace program to be notified of kernel events
(i.e. setting the brightness), but this is not implemented yet.
Issue ev3dev/lms2012-compat#9

user: add support for user LEDs

---

sensors/ev3_uart_sensor.h
sensors/ev3_uart_sensor_defs.c

This adds sensor definitions for Fatcatlab sensors. These are all
EV3/UART type sensors.
I don't have the Gesture Sensor, so it is missing from the list.

sensors: add Fatcatlab sensors

---

ev3/legoev3_motor.c

See rhempel/ev3dev-lang-python#241.
This is more of a question than an actual PR. Would this be the correct way to delay setting the `stalled` state?

Wait 100ms before setting the stalled flag

---

brickpi/brickpi_i2c_sensor.c

This is ugly hack and only for ms_absolute_imu. For mi-xg1300l it's far worse than that.
I don't really expect that @dlech merges it but this is the minimum code to make it work.
It relies on two facts:
- ms_imu uses only send_cmd_post_cb from ops
- in this function it only uses nxt_i2c_sensor_data.lego_sensor_device.mode_info
So the workaround creates mockup nxt_i2c_sensor_data with only this field filled. 
The bad thing is that everytime send_cmd is called a rather big mockup nxt_i2c_sensor_data structure is declared.
I have no means to test it (no ms_absolute_imu).
I am going to start working on i2c adapter driver in the free time (if nobody is working on it).

BrickPi workaround to make ms-absolute-imu work before i2c adapter driver
